/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomNav: typeof import('./src/components/BottomNav.vue')['default']
    ChinaMap: typeof import('./src/components/ChinaMap.vue')['default']
    CountyMap: typeof import('./src/components/CountyMap.vue')['default']
    CycleStatusBar: typeof import('./src/components/CycleStatusBar.vue')['default']
    FirstTimeExperience: typeof import('./src/components/FirstTimeExperience.vue')['default']
    GameBottomBar: typeof import('./src/components/GameBottomBar.vue')['default']
    GuofengButton: typeof import('./src/components/guofeng/GuofengButton.vue')['default']
    GuofengCard: typeof import('./src/components/guofeng/GuofengCard.vue')['default']
    HeadquartersSelector: typeof import('./src/components/HeadquartersSelector.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeIcon: typeof import('./src/components/icons/HomeIcon.vue')['default']
    HometownModal: typeof import('./src/components/HometownModal.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MapIcon: typeof import('./src/components/icons/MapIcon.vue')['default']
    PlayerAvatar: typeof import('./src/components/PlayerAvatar.vue')['default']
    RankIcon: typeof import('./src/components/icons/RankIcon.vue')['default']
    RideIcon: typeof import('./src/components/icons/RideIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeamIcon: typeof import('./src/components/icons/TeamIcon.vue')['default']
    TerritoryDetailPopup: typeof import('./src/components/TerritoryDetailPopup.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    VanIcon: typeof import('vant/es')['Icon']
    WarProgressOverlay: typeof import('./src/components/WarProgressOverlay.vue')['default']
    WeekStatusBar: typeof import('./src/components/WeekStatusBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
